# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=30)),
                ('street_name', models.CharField(max_length=50)),
                ('street_no', models.IntegerField()),
                ('suburb_name', models.CharField(max_length=30)),
                ('municipality_name', models.CharField(max_length=30)),
                ('province_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AvgMunicConsumption',
            fields=[
                ('munic_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('avg_reading', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('meter_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField()),
                ('date', models.DateTimeField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Consumer')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Consumer'),
        ),
    ]
