# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerDynamicData',
            fields=[
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Consumer')),
                ('average', models.FloatField()),
                ('optimal_point', models.FloatField()),
                ('average_fopt', models.FloatField(default=0.0)),
                ('average_diff', models.FloatField(default=0.0)),
                ('n', models.IntegerField(default=1)),
            ],
        ),
    ]
