# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consumerdynamicdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerdynamicdata',
            name='consumption',
            field=models.FloatField(default=250),
            preserve_default=False,
        ),
    ]
