# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161001_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='value',
            new_name='reading',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='meter_no',
        ),
    ]
