# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_consumerdynamicdata_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerdynamicdata',
            name='consumption',
        ),
    ]
