# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_address_street_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgMunicConsumption',
            fields=[
                ('munic_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('avg_reading', models.FloatField()),
            ],
        ),
    ]
