# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_consumerdynamicdata_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loosers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('indiv_loss', models.BooleanField()),
                ('group_loss', models.BooleanField()),
                ('indv_score', models.FloatField()),
                ('group_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('indiv_win', models.BooleanField()),
                ('group_win', models.BooleanField()),
                ('indv_score', models.FloatField()),
                ('group_score', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='group_name',
            field=models.CharField(default='Group1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winners',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Consumer'),
        ),
        migrations.AddField(
            model_name='loosers',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Consumer'),
        ),
    ]
