# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_avgmunicconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='consumer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Consumer'),
            preserve_default=False,
        ),
    ]
